apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: cloudpulse
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'cloudpulse-api'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['cloudpulse-api:80']
