apiVersion: v1
kind: ConfigMap
metadata:
  name: setup-tables-script
  namespace: cloudpulse
data:
  # script that initializes the database
  setup.sh: |
    #!/bin/sh
    echo "Waiting for DynamoDB Service..."
    # 1. Wait loop: Keeps trying to access DynamoDB until it responds.
    #    This prevents the job from failing immediately if the DB pod is starting up.
    until aws dynamodb list-tables --endpoint-url http://dynamodb-local:8000 --region us-east-1 > /dev/null 2>&1; do
      echo "DynamoDB not ready yet..."
      sleep 2
    done

    echo "DynamoDB is up. Creating tables..."

    # 2. Create 'targets' table
    #    ' || true' ensures the script doesn't exit if the table already exists.
    #    This makes the job idempotent (can be managed/re-run safely).
    aws dynamodb create-table --endpoint-url http://dynamodb-local:8000 --region us-east-1 \
      --table-name cloudpulse-targets-local \
      --attribute-definitions AttributeName=id,AttributeType=S \
      --key-schema AttributeName=id,KeyType=HASH \
      --billing-mode PAY_PER_REQUEST || true

    # 3. Create 'results' table
    aws dynamodb create-table --endpoint-url http://dynamodb-local:8000 --region us-east-1 \
      --table-name cloudpulse-probe-results-local \
      --attribute-definitions AttributeName=target_id,AttributeType=S AttributeName=timestamp,AttributeType=N \
      --key-schema AttributeName=target_id,KeyType=HASH AttributeName=timestamp,KeyType=RANGE \
      --billing-mode PAY_PER_REQUEST || true

    echo "Tables initialized."
---
# job: run a container once
apiVersion: batch/v1
kind: Job
metadata:
  name: setup-tables
  namespace: cloudpulse
spec:
  template:
    spec:
      containers:
        - name: setup-tables
          image: amazon/aws-cli
          command: ["/bin/sh", "/scripts/setup.sh"]
          env:
            # dummy credentials are required by the AWS CLI even for local DynamoDB
            - name: AWS_ACCESS_KEY_ID
              value: "dummy"
            - name: AWS_SECRET_ACCESS_KEY
              value: "dummy"
            - name: AWS_REGION
              value: "us-east-1"
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
        - name: script-volume
          configMap:
            name: setup-tables-script
            defaultMode: 0755
