global:
  # how often prometheus scrapes metrics from all configured targets
  scrape_interval: 5s

  # how often prometheus evaluates alerting/recording rules
  # we don't have rules yet, but keeping this aligned with scrape_interval is fine
  evaluation_interval: 5s

scrape_configs:
  - job_name: "cloudpulse_api" # logical name for this scrape target group

    # static list of endpoints for prometheus to scrape
    # in docker compose, "api" resolves to the api container hostname
    static_configs:
      - targets: ["api:8080"]
